### ISSUE TITLE
Kubernetes Cluster Mode Inquiry

### ISSUE THREAD

**Issue by CSP197** [TwinProduction/gatus#103]
Hello - 
I came across this project, and wanted to inquire about the cluster modes in the Kubernetes deployment configuration. By setting the cluster mode as `out`, will Gatus only monitor the services in one single cluster as defined in the `./kube/config` file, or is it possible for Gatus to access multiple clusters as listed in the `.kube/config` file?

For example, if the `~/.kube/config` file contains information about 2 clusters, is Gatus able to monitor services running in both clusters?

Thanks,

**Comment by TwinProduction** [comment]
@CSP197 I've never tried it myself, but unless there's been recent changes to kubeconfig, the way configuring access to multiple clusters work if by using contexts, and the active context is defined by the `current-context` property in `~/.kube/config`.

By default, using `Gatus` with `kubernetes.cluster-mode` set to `out` would most likely leverage whatever context is defined by `current-context` rather than iterate through each cluster configurations defined in the kubeconfig file.
