### ISSUE TITLE
Increase the number of uptime badge colors 

### ISSUE THREAD

**Issue by nikhil-vinod-gupta** [TwinProduction/gatus#125]
Hi,

1. /api/v1/statuses doesn't provide the details about the uptime. For getting the uptime user will have to use /api/v1/statuses/{key} but if there are 100s of services being monitored then user will have to get the keys first using /api/v1/statuses and then get the uptime in loop using /api/v1/statuses/{key}. So can /api/v1/statuses can be changed to accept argument i.e. /api/v1/statuses?uptime=true to provide uptime of all the services.

2. uptime badges are always green in color. There should be an option to change the color based on the uptime percentage i.e. if it is 100% then green, if 95% <= uptime < 100% then yellow, if uptime < 95% then red and should be configurable.

**Comment by TwinProduction** [comment]
Hello @nikhil-vinod-gupta 

1. You're correct, in fact, the uptime is purposely hidden from the response in `/api/v1/statuses` because that data is not used on the main dashboard. Conversely, `/api/v1/statuses/{key}` does use it, therefore, it is exposed:

https://github.com/TwinProduction/gatus/blob/5bf560221f40adb1c60c29d39b72caac974ca1a7/core/service-status.go#L38-L43

2. In fact, the badge turns red when the availability drops below 80%:

https://github.com/TwinProduction/gatus/blob/5bf560221f40adb1c60c29d39b72caac974ca1a7/controller/badge.go#L63-L67
That being said, I'm open to having more badge color to better reflect the uptime percentage.
