### ISSUE TITLE
Support wecom alerting provider

### ISSUE THREAD

**Issue by Chandler-Lu** [TwinProduction/gatus#145]
Hello, I'm a Chinese and my team use Wechat Company (Wecom) to watch status of servers.

I'm not a developer, I try to write wecom alerting code and it work's fine on my machine. But because of my Go language level, there may be many exceptions that have not been handled. If possible, I hope it can be merge into the official code. Thanks.

Push to Wecom, we need 3 necessary parameters, `Aid`, `Cid` and `Secret`.

``` go
package wecom

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"

	"github.com/TwinProduction/gatus/alerting/alert"
	"github.com/TwinProduction/gatus/alerting/provider/custom"
	"github.com/TwinProduction/gatus/core"
)

// AlertProvider is the configuration necessary for sending an alert using Wecom
type AlertProvider struct {
	Aid    string `yaml:"aid"`
	Cid    string `yaml:"cid"`
	Secret string `yaml:"secret"`
	ToUser string `yaml:"touser"` // Not necessary
	ToParty string `yaml:"toparty"` // Not necessary

	// DefaultAlert is the default alert configuration to use for services with an alert of the appropriate type
	DefaultAlert *alert.Alert `yaml:"default-alert"`
}
```

Then, we need use `Cid` and `Secret` to get `accessToken`.

``` go
	var wetoken string
	wetoken = fmt.Sprintf("%s%s%s%s", "https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=", provider.Cid, "&corpsecret=", provider.Secret)
	client := &http.Client{}
	req, err := http.NewRequest("GET", wetoken, nil)
	resp, err := client.Do(req)
	if err != nil {
		fmt.Println("Failure : ", err)
	}
	respBody, _ := ioutil.ReadAll(resp.Body)
	r := make(map[string]interface{})
	json.Unmarshal([]byte(respBody), &r)
	accessToken := r["access_token"]
```

Last, use `accessToken` to push.

``` go
	return &custom.AlertProvider{
		URL:    fmt.Sprintf("https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=%s", accessToken),
		Method: http.MethodPost,
		Body: fmt.Sprintf( TODO:BODY ),
		Headers: map[string]string{"Content-Type": "application/json"},
	}
```

If `ToUser` and `ToParty` are empty, the `BODY` will be:

``` json
{
	"agentid": %s,
	"msgtype": "text",
	"text": {
		"content": "%s"
	},
	"duplicate_check_interval": 180
}
```

If one of the two is empty, the `BODY` will be:

``` json
{
	"toparty": %s,
	"agentid": %s,
	"msgtype": "text",
	"text": {
		"content": "%s"
	},
	"duplicate_check_interval": 180
}
```

or 

``` json
{
	"touser": %s,
	"agentid": %s,
	"msgtype": "text",
	"text": {
		"content": "%s"
	},
	"duplicate_check_interval": 180
}
```

If both parameters are not empty, the `BODY` will be:

``` json
{
	"touser": %s,
	"toparty": %s,
	"agentid": %s,
	"msgtype": "text",
	"text": {
		"content": "%s"
	},
	"duplicate_check_interval": 180
}
```

**Comment by TwinProduction** [comment]
@Chandler-Lu Is there any chance you can try to get it working with the `custom` alerting provider, and let me know what your configuration looks like once you get it working? That'll make it much easier for me to add support for WeCom.

The documentation for the `custom` alerting provider can be found here: https://github.com/TwinProduction/gatus#configuring-custom-alerts

**Comment by Chandler-Lu** [comment]
> @Chandler-Lu Is there any chance you can try to get it working with the `custom` alerting provider, and let me know what your configuration looks like once you get it working? That'll make it much easier for me to add support for WeCom.
> 
> The documentation for the `custom` alerting provider can be found here: https://github.com/TwinProduction/gatus#configuring-custom-alerts

As far as I know, the `custom` alerting provider can't complete a GET and a POST operation?

**Comment by TwinProduction** [comment]
@Chandler-Lu In fact, you can pretty much do everything you can do with services, with the custom alerting provider.

```yaml
alerting:
  custom:
    url: "https://example.org"
    method: "GET"
    headers:
      Some-Header: 12345
    body: |
      {
        "text": "[ALERT_TRIGGERED_OR_RESOLVED]: [SERVICE_NAME] - [ALERT_DESCRIPTION]"
      }
```

**Comment by Chandler-Lu** [comment]
But how to transfer parameter? Get accessToken through GET, then use accessToken to push through POST operation

**Comment by TwinProduction** [comment]
Ah I see, I believe you might be looking at the wrong documentation @Chandler-Lu 

I'm having a bit of trouble navigating through the documentation, since WeCom was recently renamed from WeChat Work, but basically, you need to look for an implementation that uses a webhook instead.

Webhooks are a way to send messages in one request, while what you're requesting requires 2 requests (one to get the accessToken, and one to push the message with the accessToken).

I think this page might have some relevant information: https://work.weixin.qq.com/api/doc/90000/90136/91770

**Comment by Chandler-Lu** [comment]
Sorry, maybe we are not talking about the same service.
`bot` serves a **group**, `the application message` serves **all members who in my team**.

GET access token: https://work.weixin.qq.com/api/doc/90000/90135/91039
POST message: https://work.weixin.qq.com/api/doc/90000/90135/90236#接口定义

**Comment by TwinProduction** [comment]
I just went over documentation with Google Translator, and in fact, it seems like a webhook is mapped to a single group in the bot's detail page.

![image](https://user-images.githubusercontent.com/15699766/127601439-4e90187f-480f-41ba-93bc-7a43735513ea.png)

Then again, I'm not sure if it's a translation issue, but if it is, I'm not willing to implement a hack just for WeCom to support making 2 requests one after the other. All other alerting providers only send one request.

I'm fairly sure that using the webhook feature should let you select a group where the message will be sent, because most chatting platform (Slack, Discord, etc.) do the same thing; the only thing that you use as an input is the webhook, and in the bot configuration, the webhook is mapped to a channel where the message will be sent.

Anyways, try to investigate, and if it turns out that my hunch is right, it should be fairly simple to implement an alerting provider for the webhook.

**Comment by Chandler-Lu** [comment]
Thank you for your reply. I'll try to use BOT to finish this things.

In addition, I have the other suggestion. When the list take up full of one page, if I want to view history status, I need to drag the page to the bottom and click the button. It is inconvenience. I don't know if it is possible to optimize the position of the button.

**Comment by TwinProduction** [comment]
@Chandler-Lu Did you manage to do it?

**Comment by Chandler-Lu** [comment]
> @Chandler-Lu Did you manage to do it?

Sorry, I don't know how to optimize it.

**Comment by TwinProduction** [comment]
Got it, well thank you for trying :) 

If somebody tries to implement it, I'll link this issue to them; it should give them some help.
