### ISSUE TITLE
Feature Request: Add the option to give an incident report.

### ISSUE THREAD

**Issue by embedvr** [TwinProduction/gatus#165]
Hello! I have begun using Gatus for providing a status page to my customers. I would really like to have a place to serve an incident report to my customers where I can explain what went wrong and such.  I presume this should also be sent in alerts to places like Discord. Would also like a past incidents list / page for seeing past incidents.

An example of something like this would be Statuspage.io or Cachet.

**Comment by TwinProduction** [comment]
To be perfectly transparent with you, in the foreseeable future, I want to keep Gatus' UI read-only.

Besides the trouble that this might cause with users relying on in-memory storage, the main reason is because I'm currently working on a separate project that will have a UI for managing Gatus' configuration, which may include incident reports further down the road.

Nothing's official, but long story short, I intend on making a SaaS out of this project for people to configure and deploy a Gatus instance on a remote infrastructure.

Anyways, the point I'm getting at is, I'd rather avoid having to manage writes on two fronts for the moment. That's not to say that I won't change my mind later and decide to implement it on Gatus instead, but that won't be in the near future at least.

**Comment by TwiN** [comment]
just FYI, I'm planning on implementing something like this soon.

Configuration would look like this:
```yaml
announcements:
  - timestamp: "2023-08-21T19:15:04Z"
    title: ""
    description: ""
    active: true # active announcements are shown at the top of Gatus
```
