### ISSUE TITLE
Need more debug

### ISSUE THREAD

**Issue by m4dm4rtig4n** [TwinProduction/gatus#170]
Hello,

I have some services reporting errors 400, and I would like to know if it is possible to retrieve the result in question from the test in order to debug more easily.

I am going in debug, but I don't have much more information in the end

**Comment by TwinProduction** [comment]
Hello @m4dm4rtig4n, you can always use the `[BODY]` placeholder to help with debugging.

By default, if a condition fails, its value will be included in the resolved condition:
![image](https://user-images.githubusercontent.com/15699766/132929624-45157e27-3313-47bd-83a5-ce5b4a86c3b0.png)

Do note that if the resolved parameter is too long, it will be truncated.

For the sake of verbosity, the full body used to be both printed in the logs as well as persisted in the case of an error, but it is no longer the case because some people monitor endpoints with a 100KB+ response body size.
