### ISSUE TITLE
Show what condition was failing when sending alert

### ISSUE THREAD

**Issue by hurnhu** [TwinProduction/gatus#19]
So I had alerts come in for 3 of the sites i monitor over the weekend. 

But I didn't look at them until this morning. 
All I know is something happened to make the alert send.

I have 2 conditions set, its not uncommon for my sites to get > 1000 ever so often.
After 2 failed checkins it will alert me via teams of the issue.

```
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
```

Is it possible to say what condition was invalid in the alert to me via teams? (via the description of the custom alert)
Also to see what that value of the failing condition was.

**Comment by TwinProduction** [comment]
> Is it possible to say what condition was invalid in the alert to me via teams? (via the description of the custom alert)
> Also to see what that value of the failing condition was.

Ah, you're using the `custom` alerting provider for Microsoft Teams.

Slack's alerting provider already does what you're looking for:
![image](https://user-images.githubusercontent.com/15699766/95208510-31274980-07b7-11eb-9357-30ab00cbce68.png)

So a similar solution could be implementing an alerting provider specifically for Teams instead, but it is true that another placeholder for custom alerting could come in handy.

Currently, the placeholders supported for custom alerts are the following:
- `[ALERT_DESCRIPTION]`
- `[SERVICE_NAME]`
- `[ALERT_TRIGGERED_OR_RESOLVED]`

These placeholders are all resolved [here](https://github.com/TwinProduction/gatus/blob/230c8821eccc8536601401964a07f60aadb5485b/alerting/provider/custom/custom.go#L32).


We could add another placeholder, like `[FAILED_CONDITIONS]`, `[SUCCESSFUL_CONDITIONS]` and/or `[CONDITION_RESULTS]`, but the issue would be what the format would look like (separated by `\n`? With a `-` at the beginning of each conditions? With support for markdown?)

I believe that implementing an alerting provider for `teams` rather than using the `custom` alerting provider is the easiest and most flexible approach.

If nobody picks up this task within a few days, I might work on it myself on my free time, but I've never used Teams myself so it might be better if somebody else could pick up this feature request.

**Comment by hurnhu** [comment]
I can start looking into it.
TBH i dont know why anyone would want to use teams.

I'm only using it because of work and not by choice.

**Comment by TwinProduction** [comment]
@hurnhu since you mentioned you might implement a provider specifically for Microsoft Teams, I'll close this issue. If you do decide to work on it, please create a new issue 🙏
