### ISSUE TITLE
Allow for context root

### ISSUE THREAD

**Issue by just1689** [TwinProduction/gatus#45]
Good day 

Awesome project.

I have an idea / suggestion:

How would you feel about a context root?

For example if someone wanted to host on `/status/`

**Comment by TwinProduction** [comment]
That could go in well under the `web` configuration introduced by #43

**Comment by just1689** [comment]
@TwinProduction I've modified the code to support this feature. Would you mind me going ahead and submitting a pull request?

**Comment by just1689** [comment]
Apologies I see there is a pull request for this.

**Comment by TwinProduction** [comment]
@just1689 no problem, it happens to the best of us 😅 

Closed by #46

**Comment by TwinProduction** [comment]
Released in [v1.8.0](https://github.com/TwinProduction/gatus/releases/tag/v1.8.0)

**Comment by TwinProduction** [comment]
Hello @just1689, I released [v2.0.0](https://github.com/TwinProduction/gatus/releases/tag/v2.0.0) today, and unfortunately, I decided to remove the `web.context-path` feature.

Vue.js' router doesn't allow relative context-root, which makes it a lot more difficult to implement. Since you're the only person I know that is using this feature, I decided to forgo its existence for now.

To continue using this feature immediately, please leverage Gatus v1.x's latest version instead.

If you'd like to have this feature re-implemented in 2.x, please create another issue pointing to this ISP and I'll do my best to investigate.

**Comment by bbl232** [comment]
FWIW we were also relying on this feature as we run many copies of Gatus in our cluster and TLS certs are bound to *.domain.com we cannot add a status subdomain to our config. This is preventing us from upgrading past where we are sadly.
