### ISSUE TITLE
Autocompletion for Vim

### ISSUE THREAD

**Issue by TwinProduction** [TwinProduction/gatus#57]
Could be done in a separate repository and a link to that repository could be documented in Gatus' README

**Comment by TwinProduction** [comment]
Could probably leverage something like https://github.com/alecthomas/jsonschema to generate a JSON schema (which should work with YAML)

**Comment by nogweii** [comment]
@TwiN did you ever decide to implement this, or to skip it? Because generating a JSON schema will make things like [the YAML LSP](https://github.com/redhat-developer/yaml-language-server) work for providing the autocompletion to Vim, Emacs, VSCode and many other editors. Plus, it'd also be nice for validating the config as part of an automated deployment workflow.

**Comment by TwiN** [comment]
@nogweii I have not, however, if you'd like, you could create a feature request for this.
