### ISSUE TITLE
feature request: dark theme

### ISSUE THREAD

**Issue by rissson** [TwinProduction/gatus#99]
I'm staggered no one asked for this before! If this is a feature that could benefit to this project, I'm happy to work on it. Possibly, having a setting that default the theme to light or dark, and a button that dynamically changes it. What do you think?

**Comment by jon4hz** [comment]
A dark mode would be amazing!

**Comment by TwinProduction** [comment]
How does this look? 
![image](https://user-images.githubusercontent.com/15699766/116842563-ed5cbd00-abaa-11eb-9046-629bf2e4f80a.png)

Ignore the bottom left corner's "dark mode" message, that's just for testing purposes. I haven't decided on how the button for toggling dark mode will look like yet.

**Comment by rissson** [comment]
It does look great! I'm so excited to get to use it!

**Comment by TwinProduction** [comment]
Here's the final result

## Light mode
![image](https://user-images.githubusercontent.com/15699766/117515160-72592500-af63-11eb-92d5-6b370ff0cae3.png)

## Dark mode
![image](https://user-images.githubusercontent.com/15699766/117516232-923e1800-af66-11eb-8847-c54c51576e98.png)

## Mobile dark mode
![image](https://user-images.githubusercontent.com/15699766/117516286-b0a41380-af66-11eb-844c-798c5f6cad2c.png)

I was originally going to pick the 💡 icon instead of ☀ for light mode, but it felt too inconsistent.

---

I think that the dark mode is a bit high contrast, but I don't think it looks bad either.
What are your thoughts?

**Comment by rissson** [comment]
There is indeed quite a bit of contrast in dark mode, but it feels right, and it looks tremendous. Thanks a lot for your work again!

**Comment by Avasz** [comment]
Indeed high contrast.
 
IMO some modificatoins can be done to match Github's Dark Mode (This issue page itself). It looks almost similar to the design posted, but a bit easy going to the eyes. 
Thanks a lot for your work!

**Comment by TwinProduction** [comment]
Reduced the contrast a bit, though it's not as dark as GitHub's dark mode, I feel that it's a good in-between:
![image](https://user-images.githubusercontent.com/15699766/117579875-fe359300-b0c2-11eb-9c38-7ac29913d7c2.png)

In any case, it's not like we can't tweak the colors later.
